version: '3.8'

services:
  krona:
    build:
      context: .
      dockerfile: Dockerfile
    image: krona
    container_name: krona_container
    command: ktImportTaxonomy
volumes:
  scripts:
    driver: local
  data:
    driver: local
